#
#  Copyright (c) Honda Research Institute Europe GmbH
#
#  This file is part of ToolBOSLib.
#
#  ToolBOSLib is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  ToolBOSLib is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with ToolBOSLib. If not, see <http://www.gnu.org/licenses/>.
#
#


default:
    image: dmz-gitlab.honda-ri.de:5050/gitlabrunner/buildcontainers/hri-eu-main:latest
    interruptible: true

stages:
    - build
    - test
    - check

buildLinux:
    stage: build
    script:
        - ./ci-buildLinux.sh
    artifacts:
        paths:
            - lib
            - test

buildWindows:
    stage: build
    image: dmz-gitlab.honda-ri.de:5050/gitlabrunner/buildcontainers/hri-eu-wine:latest
    script:
        - ./ci-buildWindows.sh

test:
    stage: test
    script:
        - ./ci-test.sh

# known not to work, f.i. many checkers fail
#
#check:
#    stage: check
#    script:
#        - ./ci-check.sh
#    allow_failure: true


# EOF
